/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

/**
 *
 * @author Jonathan
 */
public class reserva extends javax.swing.JFrame {

    /**
     * Creates new form reserva
     */
    public reserva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelID = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelSala = new javax.swing.JLabel();
        jLabelObjetivo = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jLabelDemanda = new javax.swing.JLabel();
        jTextFieldID1 = new javax.swing.JTextField();
        jTextFieldUsuario = new javax.swing.JTextField();
        jTextFieldSala = new javax.swing.JTextField();
        jScrollPaneObejtivo = new javax.swing.JScrollPane();
        jTextPaneObjetivo = new javax.swing.JTextPane();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jFormattedTextFieldHora = new javax.swing.JFormattedTextField();
        jSpinnerDemanda = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelID.setText("ID");
        getContentPane().add(jLabelID);
        jLabelID.setBounds(70, 70, 69, 16);

        jLabelUsuario.setText("Usuário");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(70, 140, 44, 16);

        jLabelSala.setText("Sala");
        getContentPane().add(jLabelSala);
        jLabelSala.setBounds(70, 210, 25, 16);

        jLabelObjetivo.setText("Objetivo");
        getContentPane().add(jLabelObjetivo);
        jLabelObjetivo.setBounds(70, 280, 46, 16);

        jLabelData.setText("Data");
        getContentPane().add(jLabelData);
        jLabelData.setBounds(70, 390, 26, 16);

        jLabelHora.setText("Hora");
        getContentPane().add(jLabelHora);
        jLabelHora.setBounds(180, 390, 27, 16);

        jLabelDemanda.setText("Demanda");
        jLabelDemanda.setToolTipText("Quantidade de pessoas a ocupar a sala.");
        getContentPane().add(jLabelDemanda);
        jLabelDemanda.setBounds(70, 460, 54, 16);

        jTextFieldID1.setPreferredSize(new java.awt.Dimension(270, 24));
        getContentPane().add(jTextFieldID1);
        jTextFieldID1.setBounds(71, 96, 270, 24);

        jTextFieldUsuario.setPreferredSize(new java.awt.Dimension(270, 24));
        getContentPane().add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(71, 166, 270, 24);

        jTextFieldSala.setPreferredSize(new java.awt.Dimension(270, 24));
        getContentPane().add(jTextFieldSala);
        jTextFieldSala.setBounds(71, 236, 270, 24);

        jScrollPaneObejtivo.setViewportView(jTextPaneObjetivo);

        getContentPane().add(jScrollPaneObejtivo);
        jScrollPaneObejtivo.setBounds(71, 306, 270, 65);

        jFormattedTextFieldData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFormattedTextFieldData.setText("DD/MM/AAAA");
        getContentPane().add(jFormattedTextFieldData);
        jFormattedTextFieldData.setBounds(71, 417, 90, 20);

        jFormattedTextFieldHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        jFormattedTextFieldHora.setText("HH:mm");
        getContentPane().add(jFormattedTextFieldHora);
        jFormattedTextFieldHora.setBounds(179, 417, 91, 20);

        jSpinnerDemanda.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(jSpinnerDemanda);
        jSpinnerDemanda.setBounds(71, 483, 54, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JFormattedTextField jFormattedTextFieldHora;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelDemanda;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelObjetivo;
    private javax.swing.JLabel jLabelSala;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JScrollPane jScrollPaneObejtivo;
    private javax.swing.JSpinner jSpinnerDemanda;
    private javax.swing.JTextField jTextFieldID1;
    private javax.swing.JTextField jTextFieldSala;
    private javax.swing.JTextField jTextFieldUsuario;
    private javax.swing.JTextPane jTextPaneObjetivo;
    // End of variables declaration//GEN-END:variables
}
