/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import roombooking.*;

/**
 *
 * @author Jonathan
 */
public class UsersFrame extends javax.swing.JFrame {

    /**
     * Creates new form usuarios
     */
    public UsersFrame(DatabaseHelper helper, User currentUser) {
        initComponents();
        this.currentUser = currentUser;
        this.helper = helper;
        users = helper.getAllUsers();

        DefaultTableModel dtm = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        jTable1.setModel(dtm);

        //DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.addColumn("NOME");
        dtm.addColumn("MATRÍCULA");
        dtm.addColumn("VÍNCULO");

        users.stream().forEach((usr) -> {
            dtm.addRow(new Object[]{usr.getName(), usr.getUserID(), usr.getUserTypeDescription()});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAdicionar = new javax.swing.JButton();
        jButtonVizualizar = new javax.swing.JButton();
        jButtonInicio = new javax.swing.JButton();
        jButtonFiltrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextFieldFiltro = new javax.swing.JTextField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(932, 659));
        setResizable(false);
        setSize(new java.awt.Dimension(932, 659));
        getContentPane().setLayout(null);

        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.setOpaque(false);
        jButtonAdicionar.setPreferredSize(new java.awt.Dimension(80, 30));
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdicionar);
        jButtonAdicionar.setBounds(800, 520, 80, 30);

        jButtonVizualizar.setText("Vizualizar");
        jButtonVizualizar.setOpaque(false);
        jButtonVizualizar.setPreferredSize(new java.awt.Dimension(80, 30));
        jButtonVizualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVizualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVizualizar);
        jButtonVizualizar.setBounds(800, 570, 80, 30);

        jButtonInicio.setText("Inicio");
        jButtonInicio.setMaximumSize(new java.awt.Dimension(80, 30));
        jButtonInicio.setMinimumSize(new java.awt.Dimension(80, 30));
        jButtonInicio.setOpaque(false);
        jButtonInicio.setPreferredSize(new java.awt.Dimension(80, 30));
        jButtonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInicio);
        jButtonInicio.setBounds(80, 80, 80, 30);

        jButtonFiltrar.setText("Filtrar");
        jButtonFiltrar.setOpaque(false);
        jButtonFiltrar.setPreferredSize(new java.awt.Dimension(80, 30));
        jButtonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFiltrar);
        jButtonFiltrar.setBounds(800, 150, 80, 30);

        jTable1.setModel(new DefaultTableModel());
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(80, 190, 700, 410);

        jTextFieldFiltro.setPreferredSize(new java.awt.Dimension(6, 30));
        jTextFieldFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFiltroActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldFiltro);
        jTextFieldFiltro.setBounds(80, 150, 700, 30);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/base-00.png"))); // NOI18N
        Background.setMaximumSize(new java.awt.Dimension(933, 660));
        getContentPane().add(Background);
        Background.setBounds(0, 0, 932, 659);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrarActionPerformed
        // TODO add your handling code here:
        users = helper.getUsersLike(jTextFieldFiltro.getText());
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }

        users.stream().forEach((usr) -> {
            dtm.addRow(new Object[]{usr.getName(), usr.getUserID(), usr.getUserTypeDescription()});
        });

    }//GEN-LAST:event_jButtonFiltrarActionPerformed

    private void jButtonVizualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVizualizarActionPerformed
        // TODO add your handling code here:
        new UserFrame(helper, currentUser, users.get(jTable1.getSelectedRow())).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVizualizarActionPerformed

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        // TODO add your handling code here:
        new UserFrame(helper, currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButtonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioActionPerformed
        // TODO add your handling code here:
        new StartFrame(helper, currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonInicioActionPerformed

    private void jTextFieldFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFiltroActionPerformed
        // TODO add your handling code here:
        jButtonFiltrarActionPerformed(evt);
    }//GEN-LAST:event_jTextFieldFiltroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersFrame(new DatabaseHelper(), new User()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonFiltrar;
    private javax.swing.JButton jButtonInicio;
    private javax.swing.JButton jButtonVizualizar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldFiltro;
    // End of variables declaration//GEN-END:variables
    private DatabaseHelper helper;
    private ArrayList<User> users;
    private User currentUser;
}
